#page title
page_title                                :  Recycle Buddy                            # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1536261191                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Recycle Buddy                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : FREE                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Lets this app help you to do your part and recycle more


# Information About Yourself
your_name                                 : Richard Moult                                
your_city                                 : Melbourne                                
email_address                             : recycle.buddy.au@gmail.com


# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Information
    description                           : The app information on over 160 items and 79 councils in Victoria with ways you can or cannot recycle them.
    fontawesome_icon_name                 : magic
    
  - title                                 : Dark Mode
    description                           : This app supports dark mode so its a little easier on the eyes
    fontawesome_icon_name                 : info-circle

  - title                                 : Large Font Support / Accessibility
    description                           : The app supports larger fonts for that than need it and also voice over for those that need to hear the interface.
    fontawesome_icon_name                 : info-circle

# Theme Settings
topbar_color                              : "#ffffff"
topbar_transparency                       : 1.0
topbar_title_color                        : "#ffffff"

cover_image                               : assets/white.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 1.0

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#F5F7F8"

link_color                                : "#1d63ea"

app_title_color                           : "#000000"
app_price_color                           : "#000000"
app_description_color                     : "#000000"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown